name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Fazer upload do build
        uses: actions/upload-pages-artifact@v4
        with:
          path: './build'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Fazer deploy
        id: deployment
        uses: actions/deploy-pages@v4