name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test -- --watchAll=false

      - name: Gerar build
        run: npm run build