name: Discord Alert

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\"🚀 Novo commit realizado na branch main do projeto-devops!\"}" \
            "$DISCORD_WEBHOOK"